server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/staff_management?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j2 # stat监控统计，和 DruidConfig 中的 statViewServlet 有关
  mvc:
    format:
      date: YYYY-MM-DD HH:mm:ss
mybatis:
  mapper-locations: "classpath:mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql